const mongoose = require('mongoose');
const Schema = mongoose.Schema;

let userPointsSchema = new Schema({

  "username"                : { type: String, default:  ''},
  "chatId"                  : { type: String, default: '',index:true },
  "points"                  : { type: Number, default: 0},
  "level"                   : { type: String, default: '' },
  "user_id"                 : { type : String, default : "",index:true},
  "first_name"              : { type : String, default : ""},
  "profile_pic"             : { type : String, default : ""},
  "bankOrExchangeImg"       : { type : String, default : ""},
   "banktype"               : {type:String,default:''},
   "bankname"               : {type:String,default:''},
  "reward_start_date"       : { type: Date, default : ''},
  "last_claimed_date"       : { type: Date, default: ''},
  "prev_day"                : { type: Number,default: 0},
  "next_day"                : { type: Number,default: 0},
  "score"                   : { type: Number, default: 0},
  "tap_energy_level"        : { type: Number, default: 1000},  
  "tap_energy"              : { type: Number, default: 1},
  "multitap_level"          : { type: Number, default: 1},
  "multienergy_level"       : { type: Number, default: 1},
  "refferal_id"             : { type: String, default: "",index:true },
  "refferer_id"             : { type: String, default: ""},
  "claim_status"            : {type:Number,default:0},
  "reward_status"           : { type:Number , default:0}, 
  "current_energy"          : { type: Number, default: 1000},   //current energy user have
  "full_energy_created_at"  : { type: Date, default: "" },
  "full_energy_refilled_at": { type: Date, default: Date.now },
  "cipher_claimed_date": { type: Date, default: "" },
  "full_energy_count"       : { type: Number, default: 6 },
  "tele_channel_joined" : {type : Number, default : 0},
  "you_video_sts1"   :{ type :Number , default : 0},
  "you_video_sts2"   :{ type :Number , default : 0},
  "you_video_sts3"   :{ type :Number , default : 0},
  "videoId1"         : {type:String,default:''},
  "videoId2"         : {type:String,default:''},
  "videoId3"         : {type:String,default:''},
  "key" : {type : Number, default : 0},
  "combo_points"     :{ type:Number,default:0},
  "combo_profit"     :{ type:Number,default:0},
  "combo_lvl"        :{type :Number,default:0},
  "combo_lvlname"     : {type:String, default:''},
  "combo_prev_lvl"     :{ type:Number,default:0},
  "combo_prev_points"  :{ type:Number,default:0},
  "combo_prev_profit"  :{ type:Number,default:0},
  "selected_cards": [{ 
    level_name: String,
    level: Number,
    overall_profit: Number,
    profit_per_hour: Number,
    created_at: Date,
    updated_at: Date,
    image: String,
    category: String
  }],
    "subs"  :{ type:Number,default:0},
    "bnkSts"  :{ type:Number,default:0},
    "insts"   :{ type:Number,default:0},
   "combo_rwd_sts"  :{ type:Number,default:0},
   "combo_reward_date":{ type: Date, default: ""},
   "created_at"              : { type: Date, default: Date.now },
  "updated_at"              : { type: Date, default: Date.now },
  "lastRewardTime"          : { type: Date, default: null }
}, {"versionKey" : false});

module.exports = mongoose.model('user_points', userPointsSchema, 'user_points');